server:
  port: 8080


spring:
  # redis
  redis:
    host: 62.234.221.210
    port: 2088
    database: 0
    timeout: 1800000
    password: gYEewWLM1p
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间（负数表示没限制）
        max-idle: 5
        min-idle: 0
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.221.210:3306/read_chat?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: read_chat
    password: nFsdzj8ZR5LeJXLN
    hikari:
      connection-timeout: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  # 配置映射类所在的包名
  type-aliases-package: top.devinwang.readChat.mapper
  # 配置 mapper xml文件所在的路径
  mapper-locations: classpath:mapper/**/*.xml

# 设置 JWT 密钥和过期时间 过期时间为100年
jwt:
  expire: 3075840000000
  signKey: ojDIyCjvaE

# 微信的相关密钥

weixin:
  appid: 'wx825685dd56d3e091'
  secret: 'cbc66238c5242e9a0e80a50867d33e04'

# oss相关信息
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tRs5H7TFJdo3YrrBEh1
      keySecret: 3c3Boua5hsR4XfJEORchjDI2JA6FSz
      bucketName: devinwang

# 百度云OCR
baidu:
  app_id: 31075170
  app_key: lCOC8O6GLowRGucojjte4tk0
  secret_key: jXAifG1hPAwlyXylyHdQXrFOjust73Q4

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
