server:
  port: 8080


spring:
  # redis
  redis:
    host: 
    port: 
    database: 0
    timeout: 1800000
    password: gYEewWLM1p
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间（负数表示没限制）
        max-idle: 5
        min-idle: 0
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
    hikari:
      connection-timeout: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  # 配置映射类所在的包名
  type-aliases-package: top.devinwang.readChat.mapper
  # 配置 mapper xml文件所在的路径
  mapper-locations: classpath:mapper/**/*.xml

# 设置 JWT 密钥和过期时间 过期时间为100年
jwt:
  expire: 3075840000000
  signKey: ojDIyCjvaE

# 微信的相关密钥

weixin:
  appid: 
  secret: 

# oss相关信息
aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keySecret: 
      bucketName: 
# 百度云OCR
baidu:
  app_id:
  app_key: 
  secret_key: 

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
